import {AbsoluteFill,Easing,Img,interpolate,spring,staticFile,useCurrentFrame} from "remotion";
import config from "../projects/hk-market-close/project.config";
import {hkMarketSnapshot20260828 as d} from "./data/hkMarketSnapshot20260828";

const C=config.brand.colors; const FONT=config.brand.fonts.fallback;
const clamp={extrapolateLeft:"clamp",extrapolateRight:"clamp"} as const;
const tone=(n:number)=>n>=0?C.success:C.error;
const Card:React.FC<React.PropsWithChildren<{style?:React.CSSProperties;delay?:number}>>=({children,style,delay=20})=>{const f=useCurrentFrame();const p=spring({frame:f-delay,fps:30,config:{damping:18,stiffness:120}});return <div style={{border:"1px solid rgba(101,151,190,.48)",borderRadius:18,background:"linear-gradient(145deg,rgba(4,22,43,.94),rgba(2,12,27,.92))",boxShadow:"inset 0 0 32px rgba(39,200,255,.045)",opacity:p,transform:`translateY(${(1-p)*24}px)`,overflow:"hidden",...style}}>{children}</div>};
const Num:React.FC<{v:number;delay?:number;digits?:number}>=({v,delay=20,digits=2})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+34],[0,1],{...clamp,easing:Easing.out(Easing.cubic)});return <>{(v*p).toLocaleString("en-US",{minimumFractionDigits:digits,maximumFractionDigits:digits})}</>};
const Line:React.FC<{pts:readonly number[];delay:number;color?:string;area?:boolean}>=({pts,delay,color=C.success,area=false})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+46],[0,1],clamp);const w=500,h=160,min=Math.min(...pts),max=Math.max(...pts),xy=pts.map((v,i)=>`${i*w/(pts.length-1)},${h-10-(v-min)/(max-min||1)*(h-22)}`).join(" ");return <svg width="100%" height="100%" viewBox={`0 0 ${w} ${h}`} preserveAspectRatio="none"><defs><linearGradient id={`g${delay}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor={color} stopOpacity=".32"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient><clipPath id={`c${delay}`}><rect width={w*p} height={h}/></clipPath></defs><g clipPath={`url(#c${delay})`}>{area&&<polygon points={`0,${h} ${xy} ${w},${h}`} fill={`url(#g${delay})`}/>}<polyline points={xy} fill="none" stroke={color} strokeWidth="4" strokeLinejoin="round" strokeLinecap="round" style={{filter:`drop-shadow(0 0 6px ${color})`}}/></g></svg>};
const Donut:React.FC<{value:number;delay:number;color?:string}>=({value,delay,color=C.accent})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+40],[0,value],clamp);return <svg viewBox="0 0 100 100"><circle cx="50" cy="50" r="34" fill="none" stroke="#24354b" strokeWidth="14"/><circle cx="50" cy="50" r="34" fill="none" stroke={color} strokeWidth="14" strokeLinecap="round" pathLength="100" strokeDasharray={`${p} 100`} transform="rotate(-90 50 50)"/><text x="50" y="56" textAnchor="middle" fill="white" fontSize="16" fontWeight="700">{Math.round(p)}%</text></svg>};
const Bars:React.FC<{delay:number}>=({delay})=>{const f=useCurrentFrame();return <div style={{height:90,display:"flex",alignItems:"end",gap:10}}>{d.turnoverBars.map((v,i)=>{const p=interpolate(f,[delay+i*3,delay+24+i*3],[0,1],clamp);return <div key={i} style={{flex:1,height:v*p,background:"linear-gradient(#40a9ff,#0754bd)",boxShadow:"0 0 10px #1589ff88"}}/>})}</div>};
const Missing:React.FC<{label:string}>=({label})=><div style={{color:C.textMuted,fontSize:18,lineHeight:1.5}}>{label}<div style={{color:C.accent,fontSize:14,marginTop:8}}>结构已完成 · 等待每日数据接口</div></div>;

export const HKMarketSnapshotPrototype:React.FC=()=>{const f=useCurrentFrame();const head=spring({frame:f-5,fps:30,config:{damping:18}});return <AbsoluteFill style={{background:C.background,color:C.text,fontFamily:FONT,overflow:"hidden"}}>
  <Img src={staticFile("projects/hk-market-close/images/hk-market-snapshot-bg.png")} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/><AbsoluteFill style={{background:"rgba(0,7,18,.18)"}}/>
  <div style={{position:"absolute",left:40,top:42,opacity:head,transform:`translateX(${(1-head)*-25}px)`}}><div style={{fontSize:70,fontWeight:850,letterSpacing:5}}>香港大市</div><div style={{fontSize:29,color:C.accent,letterSpacing:4}}>MARKET SNAPSHOT</div><div style={{width:230,height:3,background:C.accent,margin:"14px 0"}}/><div style={{fontSize:25}}>{d.tradeDate} / {d.weekday}</div></div>
  <Card delay={20} style={{position:"absolute",left:34,top:270,width:610,height:550,padding:25}}><div style={{fontSize:28,fontWeight:750}}>恒生指数 <span style={{fontSize:16,fontWeight:400}}>HANG SENG INDEX</span></div><div style={{fontSize:53,fontWeight:800,color:tone(d.hsi.changePct),marginTop:18}}><Num v={d.hsi.close} delay={27}/></div><div style={{fontSize:28,color:tone(d.hsi.changePct),fontWeight:750}}>{d.hsi.changePct>=0?"▲ ":"▼ "}<Num v={d.hsi.change} delay={34}/> {d.hsi.changePct>=0?"+":""}<Num v={d.hsi.changePct} delay={34}/> %</div><div style={{height:300,marginTop:30,position:"relative",borderLeft:"1px solid #7390a6",borderBottom:"1px solid #7390a6",backgroundImage:"linear-gradient(rgba(93,133,160,.13) 1px,transparent 1px)",backgroundSize:"100% 60px"}}><Line pts={d.hsi.intraday} delay={45} area color={tone(d.hsi.changePct)}/><div style={{display:"flex",justifyContent:"space-between",fontSize:15,color:C.textMuted,marginTop:8}}><span>09:30</span><span>11:30</span><span>13:30</span><span>16:00</span></div></div></Card>
  <div style={{position:"absolute",left:660,right:34,top:360,display:"grid",gap:12}}>{d.indices.map((x,i)=><Card key={x.name} delay={32+i*7} style={{height:141,padding:"15px 18px",position:"relative"}}><div style={{fontSize:21,fontWeight:750}}>{x.name}</div><div style={{fontSize:13,color:C.textMuted}}>{x.english}</div><div style={{fontSize:30,fontWeight:750,marginTop:8}}><Num v={x.value} delay={42+i*7}/></div><div style={{color:tone(x.changePct),fontWeight:750,fontSize:18}}>{x.changePct>=0?"▲ +":"▼ "}{x.changePct.toFixed(2)}%</div><div style={{position:"absolute",right:13,bottom:15,width:125,height:52}}><Line pts={x.spark} delay={50+i*7} color={tone(x.changePct)}/></div></Card>)}</div>
  <div style={{position:"absolute",left:34,right:34,top:840,display:"grid",gridTemplateColumns:"1.05fr .9fr .95fr",gap:12}}><Card delay={65} style={{height:205,padding:20}}><div style={{fontSize:22}}>大市成交额 <span style={{fontSize:13}}>MARKET TURNOVER</span></div><div style={{fontSize:34,fontWeight:800,marginTop:8}}><Num v={d.turnoverBillion*10} delay={74}/> 亿</div><div style={{position:"absolute",right:18,bottom:15,width:135}}><Bars delay={78}/></div></Card><Card delay={70} style={{height:205,padding:20}}><div style={{fontSize:22}}>沽空成交额</div><div style={{marginTop:24}}><Missing label={d.unavailable.shortSelling}/></div><div style={{position:"absolute",right:13,bottom:20,width:86,height:86,opacity:.38}}><Donut value={0} delay={80}/></div></Card><Card delay={75} style={{height:205,padding:20}}><div style={{fontSize:22}}>市场成交占比</div><div style={{marginTop:24}}><Missing label="港股通 / 其他待接入"/></div><div style={{position:"absolute",right:12,bottom:18,width:90,height:90,opacity:.38}}><Donut value={0} delay={84}/></div></Card></div>
  <div style={{position:"absolute",left:34,right:34,top:1065,display:"grid",gridTemplateColumns:".9fr .9fr 1.2fr",gap:12}}><Card delay={88} style={{height:235,padding:20}}><div style={{fontSize:23}}>市场概览</div><div style={{marginTop:30}}><Missing label={d.unavailable.breadth}/></div></Card><Card delay={93} style={{height:235,padding:20}}><div style={{fontSize:23}}>今日波幅</div><div style={{display:"grid",gridTemplateColumns:"70px 1fr",gap:7,fontSize:20,marginTop:18,color:C.textMuted}}><span>最高</span><b style={{color:C.success}}>{d.hsi.high.toFixed(2)}</b><span>最低</span><b style={{color:C.error}}>{d.hsi.low.toFixed(2)}</b><span>开市</span><b style={{color:C.text}}>{d.hsi.open.toFixed(2)}</b><span>收市</span><b style={{color:C.success}}>{d.hsi.close.toFixed(2)}</b></div></Card><Card delay={98} style={{height:235,padding:20}}><div style={{fontSize:23}}>5日走势</div><div style={{height:145,marginTop:18}}><Line pts={d.fiveDay} delay={108} color={C.accent} area/></div></Card></div>
  <Card delay={115} style={{position:"absolute",left:34,right:34,top:1320,height:465,padding:24}}><div style={{fontSize:27,fontWeight:750}}>🔥 成交额 TOP 5</div><div style={{marginTop:25,borderTop:"1px solid rgba(120,160,190,.25)",paddingTop:28}}><Missing label={d.unavailable.topTurnover}/></div>{[.92,.78,.63,.51,.42].map((v,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:18,marginTop:28,color:C.textMuted}}><span style={{width:22}}>{i+1}</span><div style={{width:180,height:14,background:"#12243a",borderRadius:9,overflow:"hidden"}}><div style={{width:`${interpolate(f,[125+i*4,155+i*4],[0,v*100],clamp)}%`,height:"100%",background:"linear-gradient(90deg,#0754bd,#2987ff)"}}/></div><span>数据接口占位</span></div>)}</Card>
  <div style={{position:"absolute",left:36,right:36,bottom:28,display:"flex",justifyContent:"space-between",color:C.textMuted,fontSize:16}}><span>数据截至香港时间 16:00</span><span>来源：新华社 · FT · ET Net | 原型 v001</span></div>
 </AbsoluteFill>};
