import {AbsoluteFill,Easing,Img,interpolate,spring,staticFile,useCurrentFrame} from "remotion";
import config from "../projects/hk-market-close/project.config";
import {hkMarketBreadth20260828 as d} from "./data/hkMarketBreadth20260828";

const C=config.brand.colors;const FONT=config.brand.fonts.fallback;const clamp={extrapolateLeft:"clamp",extrapolateRight:"clamp"} as const;
const Card:React.FC<React.PropsWithChildren<{style?:React.CSSProperties;delay:number}>>=({children,style,delay})=>{const f=useCurrentFrame();const p=spring({frame:f-delay,fps:30,config:{damping:19,stiffness:125}});return <div style={{border:"1px solid rgba(92,148,190,.5)",borderRadius:18,background:"linear-gradient(145deg,rgba(4,21,42,.95),rgba(2,12,27,.93))",boxShadow:"inset 0 0 34px rgba(39,200,255,.04)",opacity:p,transform:`translateY(${(1-p)*24}px)`,overflow:"hidden",...style}}>{children}</div>};
const Count:React.FC<{n:number;delay:number;digits?:number}>=({n,delay,digits=0})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+35],[0,1],{...clamp,easing:Easing.out(Easing.cubic)});return <>{(n*p).toLocaleString("en-US",{minimumFractionDigits:digits,maximumFractionDigits:digits})}</>};
const Ring:React.FC=()=>{const f=useCurrentFrame();const total=d.breadth.up+d.breadth.down+d.breadth.flat;const p=interpolate(f,[35,82],[0,1],clamp);const a=d.breadth.up/total*100,b=d.breadth.down/total*100,c=d.breadth.flat/total*100;return <svg viewBox="0 0 200 200"><circle cx="100" cy="100" r="72" fill="none" stroke="#15283e" strokeWidth="26"/><g transform="rotate(-90 100 100)" pathLength={100}><circle cx="100" cy="100" r="72" pathLength="100" fill="none" stroke={C.success} strokeWidth="26" strokeDasharray={`${a*p} ${100-a*p}`} strokeLinecap="butt"/><circle cx="100" cy="100" r="72" pathLength="100" fill="none" stroke={C.error} strokeWidth="26" strokeDasharray={`${b*p} ${100-b*p}`} strokeDashoffset={-a*p}/><circle cx="100" cy="100" r="72" pathLength="100" fill="none" stroke="#aab4c3" strokeWidth="26" strokeDasharray={`${c*p} ${100-c*p}`} strokeDashoffset={-(a+b)*p}/></g><text x="100" y="91" textAnchor="middle" fill="#fff" fontSize="17">涨跌比</text><text x="100" y="120" textAnchor="middle" fill="#fff" fontSize="25" fontWeight="800">{(d.breadth.up/d.breadth.down).toFixed(2)} : 1</text></svg>};
const MiniBars:React.FC<{values:readonly number[];delay:number;color:string}>=({values,delay,color})=>{const f=useCurrentFrame();const max=Math.max(...values);return <div style={{height:78,display:"flex",alignItems:"end",gap:7}}>{values.map((v,i)=>{const p=interpolate(f,[delay+i*3,delay+22+i*3],[0,1],clamp);return <div key={i} style={{flex:1,height:`${v/max*100*p}%`,background:`linear-gradient(transparent,${color})`,boxShadow:`0 0 8px ${color}77`}}/>})}</div>};
const Gauge:React.FC=()=>{const f=useCurrentFrame();const arc=interpolate(f,[90,130],[0,1],clamp);const needle=spring({frame:f-105,fps:30,config:{damping:12,stiffness:90}});const angle=-90+d.sentiment*1.8*needle;return <svg viewBox="0 0 500 220"><defs><linearGradient id="gauge" x1="0" x2="1"><stop stopColor={C.error}/><stop offset=".48" stopColor="#f2d64b"/><stop offset="1" stopColor={C.success}/></linearGradient></defs><path d="M65 190 A185 185 0 0 1 435 190" pathLength="100" fill="none" stroke="#17283d" strokeWidth="28"/><path d="M65 190 A185 185 0 0 1 435 190" pathLength="100" fill="none" stroke="url(#gauge)" strokeWidth="28" strokeDasharray={`${arc*100} 100`}/><g transform={`rotate(${angle} 250 190)`}><line x1="250" y1="190" x2="250" y2="62" stroke="#fff" strokeWidth="8" strokeLinecap="round" style={{filter:"drop-shadow(0 0 8px white)"}}/><circle cx="250" cy="190" r="13" fill="#fff"/></g><text x="250" y="158" textAnchor="middle" fill={C.success} fontSize="42" fontWeight="800">{Math.round(d.sentiment*needle)}</text><text x="250" y="186" textAnchor="middle" fill={C.success} fontSize="20">中性偏稳</text></svg>};
const Trend:React.FC=()=>{const f=useCurrentFrame();const p=interpolate(f,[132,182],[0,1],clamp);const series=[{v:d.history.up,c:C.success},{v:d.history.down,c:C.error},{v:d.history.flat,c:"#aab4c3"}];return <svg viewBox="0 0 930 250" width="100%" height="100%"><g stroke="rgba(120,160,190,.16)">{[35,90,145,200].map(y=><line key={y} x1="45" y1={y} x2="910" y2={y}/>)}</g>{series.map((s,j)=>{const min=0,max=1300;const pts=s.v.map((v,i)=>`${55+i*93},${218-(v-min)/(max-min)*185}`).join(" ");return <g key={j}><defs><clipPath id={`tc${j}`}><rect x="0" y="0" width={930*p} height="250"/></clipPath></defs><polyline points={pts} fill="none" stroke={s.c} strokeWidth="4" strokeLinejoin="round" clipPath={`url(#tc${j})`} style={{filter:`drop-shadow(0 0 5px ${s.c})`}}/></g>})}<g fill={C.textMuted} fontSize="13">{d.history.dates.map((x,i)=><text key={x} x={55+i*93} y="243" textAnchor="middle">{x}</text>)}</g></svg>};

export const HKMarketBreadthPrototype:React.FC=()=>{const f=useCurrentFrame();const head=spring({frame:f-5,fps:30,config:{damping:18}});const total=d.breadth.up+d.breadth.down+d.breadth.flat;return <AbsoluteFill style={{background:C.background,color:C.text,fontFamily:FONT,overflow:"hidden"}}><Img src={staticFile("projects/hk-market-close/images/world-map-hk-skyline.png")} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",objectPosition:"center bottom",opacity:.68}}/><AbsoluteFill style={{background:"linear-gradient(rgba(1,8,20,.88) 0%,rgba(1,8,20,.72) 76%,rgba(1,8,20,.18) 100%)"}}/>
<div style={{position:"absolute",left:40,right:40,top:48,opacity:head,transform:`translateY(${(1-head)*-25}px)`}}><div style={{fontSize:72,fontWeight:850,letterSpacing:5}}>市场温度</div><div style={{fontSize:29,color:C.accent,letterSpacing:4}}>MARKET BREADTH</div><div style={{position:"absolute",right:0,top:0,border:"1px solid #285a83",borderRadius:14,padding:"12px 22px",fontSize:22,textAlign:"center"}}>{d.tradeDate}<br/>{d.weekday}</div><div style={{fontSize:23,marginTop:28}}>结构性分化，市场情绪<span style={{color:C.success}}>中性偏稳</span>。</div></div>
<Card delay={22} style={{position:"absolute",left:34,right:34,top:285,height:475,padding:28}}><div style={{position:"absolute",left:22,top:40,width:390,height:390}}><Ring/></div><div style={{position:"absolute",left:470,right:30,top:42}}>{[{n:"上涨家数",v:d.breadth.up,c:C.success},{n:"下跌家数",v:d.breadth.down,c:C.error},{n:"平盘家数",v:d.breadth.flat,c:"#aab4c3"}].map((x,i)=><div key={x.n} style={{height:122,borderBottom:i<2?"1px solid rgba(120,160,190,.2)":"none",display:"grid",gridTemplateColumns:"1fr 130px",alignItems:"center"}}><div><div style={{fontSize:24,fontWeight:700}}><span style={{display:"inline-block",width:24,height:24,borderRadius:5,background:x.c,marginRight:15}}/>{x.n}</div><div style={{fontSize:46,fontWeight:800,color:x.c,marginLeft:42}}><Count n={x.v} delay={45+i*8}/></div></div><div style={{color:C.textMuted,fontSize:18}}>占比<br/><b style={{fontSize:26,color:x.c}}>{(x.v/total*100).toFixed(1)}%</b></div></div>)}</div></Card>
<div style={{position:"absolute",left:34,right:34,top:780,display:"grid",gridTemplateColumns:"1fr 1fr 1.35fr",gap:12}}><Card delay={62} style={{height:205,padding:22}}><div style={{fontSize:23}}>涨幅 &gt; 5%</div><div style={{fontSize:46,color:C.success,fontWeight:800}}><Count n={d.largeMove.up} delay={73}/></div><div style={{position:"absolute",right:18,bottom:18,width:135}}><MiniBars values={[18,25,34,41,53,63,74]} delay={78} color={C.success}/></div></Card><Card delay={68} style={{height:205,padding:22}}><div style={{fontSize:23}}>跌幅 &gt; 5%</div><div style={{fontSize:46,color:C.error,fontWeight:800}}><Count n={d.largeMove.down} delay={79}/></div><div style={{position:"absolute",right:18,bottom:18,width:135}}><MiniBars values={[21,31,43,56,49,62,69]} delay={84} color={C.error}/></div></Card><Card delay={74} style={{height:205,padding:22}}><div style={{fontSize:23}}>今日成交额 <span style={{fontSize:14}}>港元</span></div><div style={{fontSize:40,color:C.accent,fontWeight:800,marginTop:10}}><Count n={d.turnoverBillion*10} delay={84} digits={2}/>亿</div><div style={{color:C.error,fontSize:22,marginTop:13}}>▼ {Math.abs(d.turnoverChangePct).toFixed(1)}%</div></Card></div>
<Card delay={85} style={{position:"absolute",left:34,right:34,top:1005,height:300,padding:18}}><div style={{fontSize:24}}>市场情绪指数</div><div style={{position:"absolute",left:190,right:190,top:32,bottom:10}}><Gauge/></div><div style={{position:"absolute",left:45,bottom:42,color:C.error,fontSize:20}}>悲观<br/><span style={{color:C.textMuted}}>0–30</span></div><div style={{position:"absolute",right:45,bottom:42,color:C.success,fontSize:20,textAlign:"right"}}>乐观<br/><span style={{color:C.textMuted}}>70–100</span></div></Card>
<Card delay={118} style={{position:"absolute",left:34,right:34,top:1325,height:360,padding:22}}><div style={{fontSize:24}}>涨跌家数趋势 <span style={{fontSize:17,color:C.textMuted}}>（近10日）</span></div><div style={{position:"absolute",right:25,top:25,fontSize:15}}><span style={{color:C.success}}>● 上涨</span> <span style={{color:C.error}}>● 下跌</span> <span style={{color:"#aab4c3"}}>● 平盘</span></div><div style={{height:275,marginTop:18}}><Trend/></div></Card>
<div style={{position:"absolute",left:36,right:36,bottom:205,fontSize:14,color:C.textMuted}}>{d.disclosure}</div><div style={{position:"absolute",left:36,right:36,bottom:28,display:"flex",justifyContent:"space-between",fontSize:15,color:C.textMuted}}><span>数据截至香港时间 16:00</span><span>行情方向：新华社 · ET Net | 原型 v001</span></div>
</AbsoluteFill>};
