import {AbsoluteFill,Easing,Img,interpolate,spring,staticFile,useCurrentFrame} from "remotion";
import config from "../projects/hk-market-close/project.config";
import {hkSectorPerformance20260828 as d,type SectorItem} from "./data/hkSectorPerformance20260828";
const C=config.brand.colors;const FONT=config.brand.fonts.fallback;const clamp={extrapolateLeft:"clamp",extrapolateRight:"clamp"} as const;
const Count:React.FC<{n:number;delay:number}>=({n,delay})=>{const f=useCurrentFrame();const p=interpolate(f,[delay,delay+28],[0,1],{...clamp,easing:Easing.out(Easing.cubic)});return <>{(n*p).toFixed(2)}</>};
const Card:React.FC<React.PropsWithChildren<{style?:React.CSSProperties;delay:number;tone?:string}>>=({children,style,delay,tone=C.accent})=>{const f=useCurrentFrame();const p=spring({frame:f-delay,fps:30,config:{damping:18,stiffness:125}});return <div style={{border:`1px solid ${tone}88`,borderRadius:18,background:"linear-gradient(145deg,rgba(4,21,42,.95),rgba(2,12,27,.94))",boxShadow:`inset 0 0 34px ${tone}0b`,opacity:p,transform:`translateY(${(1-p)*25}px)`,overflow:"hidden",...style}}>{children}</div>};
const Ranking:React.FC<{items:SectorItem[];positive:boolean;delay:number}>=({items,positive,delay})=>{const f=useCurrentFrame();const color=positive?C.success:C.error;return <Card delay={delay} tone={color} style={{height:430,padding:"24px 28px"}}><div style={{fontSize:28,fontWeight:800,color}}>{positive?"行业涨幅 TOP 5":"行业跌幅 TOP 5"}</div><div style={{marginTop:16}}>{items.map((x,i)=>{const p=interpolate(f,[delay+18+i*7,delay+48+i*7],[0,1],clamp);return <div key={x.name} style={{height:68,display:"grid",gridTemplateColumns:"42px 150px 1fr 100px",gap:12,alignItems:"center",opacity:p,transform:`translateX(${(1-p)*25}px)`}}><div style={{width:35,height:35,borderRadius:99,background:`${color}99`,display:"grid",placeItems:"center",fontSize:19,fontWeight:800}}>{i+1}</div><div style={{fontSize:22}}>{x.name}</div><div style={{height:12,borderRadius:8,background:`${color}12`,overflow:"hidden"}}><div style={{height:"100%",width:`${x.weight*p}%`,background:`linear-gradient(90deg,${color}44,${color})`,borderRadius:8,boxShadow:`0 0 10px ${color}`}}/></div><div style={{fontSize:24,color,fontWeight:800,textAlign:"right"}}>{positive?"+":""}<Count n={x.changePct} delay={delay+20+i*7}/>%</div></div>})}</div></Card>};
const HeatTile:React.FC<{item:SectorItem;index:number;area:string}>=({item,index,area})=>{const f=useCurrentFrame();const delay=120+index*8;const p=spring({frame:f-delay,fps:30,config:{damping:16,stiffness:115}});const color=item.changePct>=0?C.success:C.error;const glow=interpolate(f,[delay+15,delay+42],[0,1],clamp);return <div style={{gridArea:area,border:`1px solid ${color}`,borderRadius:10,background:`linear-gradient(145deg,${color}48,${color}18)`,boxShadow:`inset 0 0 35px ${color}22,0 0 ${14*glow}px ${color}44`,display:"grid",placeItems:"center",textAlign:"center",opacity:p,transform:`perspective(700px) rotateY(${(1-p)*86}deg) scale(${.93+.07*p})`,transformOrigin:index%2?"right center":"left center",overflow:"hidden"}}><div><div style={{fontSize:27,fontWeight:800}}>{item.name}</div><div style={{fontSize:34,color,fontWeight:850,marginTop:7}}>{item.changePct>=0?"+":""}<Count n={item.changePct} delay={delay+10}/>%</div><div style={{fontSize:17,marginTop:7,color:"#d7e2ef"}}>成分股 {item.stockCount} 家</div></div><div style={{position:"absolute",inset:0,backgroundImage:"linear-gradient(90deg,transparent 49%,rgba(255,255,255,.035) 50%,transparent 51%),linear-gradient(transparent 49%,rgba(255,255,255,.035) 50%,transparent 51%)",backgroundSize:"32px 32px",opacity:.5}}/></div>};

export const HKSectorPerformancePrototype:React.FC=()=>{const f=useCurrentFrame();const head=spring({frame:f-5,fps:30,config:{damping:18}});const heat=[d.gainers[0],d.gainers[1],d.losers[0],d.gainers[2],d.gainers[3],d.losers[3],d.gainers[4],d.losers[2],d.losers[4]];const areas=["a","b","c","d","e","f","g","h","i"];return <AbsoluteFill style={{background:C.background,color:C.text,fontFamily:FONT,overflow:"hidden"}}><Img src={staticFile("projects/hk-market-close/images/hk-sector-performance-bg.png")} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover"}}/><AbsoluteFill style={{background:"linear-gradient(90deg,rgba(1,7,18,.05),rgba(1,7,18,.42) 52%,rgba(1,7,18,.72))"}}/>
<div style={{position:"absolute",left:44,top:52,opacity:head,transform:`translateY(${(1-head)*-25}px)`}}><div style={{fontSize:68,fontWeight:850,letterSpacing:4}}>板块表现</div><div style={{fontSize:27,letterSpacing:2}}>SECTOR PERFORMANCE</div><div style={{fontSize:24,color:"#a9c8e9",marginTop:18}}>{d.tradeDate} | {d.weekday}</div></div>
<div style={{position:"absolute",left:495,right:34,top:125,display:"grid",gap:16}}><Ranking items={d.gainers} positive delay={24}/><Ranking items={d.losers} positive={false} delay={48}/></div>
<Card delay={90} style={{position:"absolute",left:32,right:32,top:1030,height:740,padding:22}}><div style={{fontSize:30,fontWeight:800}}>行业热力图 <span style={{fontSize:19,fontWeight:400}}>（行业涨跌 & 成分股数量）</span></div><div style={{height:625,marginTop:20,display:"grid",gap:9,gridTemplateColumns:"1.35fr 1.25fr 1fr",gridTemplateRows:"1.1fr 1fr 1fr",gridTemplateAreas:'"a b c" "d e f" "g h i"'}}>{heat.map((x,i)=><HeatTile key={`${x.name}-${i}`} item={x} index={i} area={areas[i]}/>)}</div></Card>
<div style={{position:"absolute",left:38,bottom:95,fontSize:14,color:C.textMuted}}>{d.disclosure}</div><div style={{position:"absolute",left:38,right:38,bottom:28,display:"flex",justifyContent:"space-between",fontSize:15,color:C.textMuted}}><span>数据日期：2026-09-07</span><span>来源：HKEJ Stock360 | 原型 v001</span></div>
</AbsoluteFill>};
